In [139]:
import pandas as p
import pickle
import pickletools

%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [35]:
df = p.read_pickle('/home/matej/tcm16.pkl')

In [42]:
strainmap = {}
for allele, blid, orf, name, aliases in Strain.objects.select_related('gene').values_list(
    'allele', 'boonelab_id', 'gene__orf', 'gene__name', 'gene__aliases'):
    label = (allele or name or orf).lower()
    strainmap[orf.lower()] = label
    strainmap[blid.lower()] = label
    if allele:
        strainmap[allele.lower()] = label
    if name:
        strainmap[name.lower()] = label
    for a in aliases:
        if a not in strainmap:
            strainmap[a.lower()] = label

In [60]:
sheets = p.read_excel('/home/matej/Documents/SGS1_GI_PI_scores_6col.xlsx')

In [61]:
sheets.loc[:, 'Label'] = sheets.Label.apply(lambda x: strainmap.get(x.lower(), x))
sheets.index = sheets.Label

In [66]:
sheets = sheets.loc[~sheets.duplicated(subset='Label')]

In [69]:
sheets = sheets.reindex(index=df.columns)

In [81]:
corrs = {}
for input_ds in sheets.columns[1:2]:
    corrs[input_ds] = df.corrwith(sheets[input_ds], axis=1)

In [87]:
x = corrs['PI_Min']

In [147]:
p.DataFrame(corrs)

        PI_Min
6231  0.031620
6232  0.041250
2679  0.009177
4166  0.020359
4217  0.012814
4380  0.035593
2663  0.033185
92    0.008592
1503  0.003676
3741 -0.011269
2325  0.046005
4375 -0.057955
1485  0.005335
1247 -0.024453
645   0.008613
1793 -0.008812
4605  0.018131
2654 -0.026989
877   0.010540
3338 -0.007650
1097  0.026638
4996  0.012208
4789  0.033184
5265  0.003109
3750 -0.005375
2216 -0.001567
2061 -0.011406
1336 -0.025602
4133 -0.046654
5743 -0.002083
...        ...
3402 -0.005071
5700  0.010611
3889  0.059701
4733  0.061763
3905 -0.017552
4201 -0.017169
2711 -0.006594
861  -0.020094
2864 -0.011709
1761  0.016078
4067 -0.018710
4671 -0.063344
4659  0.005329
4791  0.014142
1724 -0.012329
4814 -0.038984
1497 -0.009222
4078  0.012072
6138 -0.007656
3543 -0.015974
1051  0.020411
3516  0.026254
226   0.003379
5171  0.038007
4620 -0.002772
4433  0.014373
6030  0.001619
5306  0.025537
1755  0.021114
1391  0.010012

[5357 rows x 1 columns]

In [100]:
mak3 = StrainData.objects.filter(strain__gene__name='MAK3', dataset__name='Living')[0]

In [103]:
dataset = Dataset.objects.get(name='Living')

In [105]:
arrays = [a.label() for a  in dataset.arrays.select_related('gene')]

In [110]:
p.DataFrame(mak3.scores, index=arrays).to_csv('/home/matej/mak3.csv')

In [111]:
def strain_map():
    strainmap = {}
    for allele, blid, orf, name, aliases in Strain.objects.select_related('gene').values_list(
            'allele', 'boonelab_id', 'gene__orf', 'gene__name', 'gene__aliases'):
        label = (allele or name or orf).lower()
        strainmap[orf.lower()] = label
        strainmap[blid.lower()] = label
        if allele:
            strainmap[allele.lower()] = label
        if name:
            strainmap[name.lower()] = label
        for a in aliases:
            if a not in strainmap:
                strainmap[a.lower()] = label
    return strainmap

In [112]:
%%timeit
strain_map()

81.1 ms ± 2.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [113]:
sm = strain_map()

In [118]:
pickle.dump(sm, open('/home/matej/sm.pkl', 'wb'))

In [120]:
%%timeit
pickle.load(open('/home/matej/sm.pkl', 'rb'))

7.41 ms ± 110 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [127]:
def strain_map2():
    strainmap = {}
    for allele, blid, orf, name, aliases in Strain.objects.select_related('gene').values_list(
            'allele', 'boonelab_id', 'gene__orf', 'gene__name', 'gene__aliases'):
        label = (allele or name or orf).lower()
        
        strainmap[blid.lower()] = label
        
        if orf.lower() != label:
            strainmap[orf.lower()] = label
        
        if allele and allele.lower() != label:
            strainmap[allele.lower()] = label
        
        if name and name.lower() != label:
            strainmap[name.lower()] = label
        
        for a in aliases:
            if a not in strainmap and len(a) < 16:
                strainmap[a.lower()] = label
    return strainmap

In [128]:
%%timeit
strain_map2()

79.1 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [129]:
sm2 = strain_map2()

In [134]:
pickle.dump(sm2, open('/home/matej/sm2v1.pkl', 'wb'), protocol=1)
pickle.dump(sm2, open('/home/matej/sm2v2.pkl', 'wb'), protocol=2)
pickle.dump(sm2, open('/home/matej/sm2v3.pkl', 'wb'), protocol=3)
pickle.dump(sm2, open('/home/matej/sm2v4.pkl', 'wb'), protocol=4)

In [135]:
%%timeit
pickle.load(open('/home/matej/sm2v1.pkl', 'rb'))

5.18 ms ± 137 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [136]:
%%timeit
pickle.load(open('/home/matej/sm2v2.pkl', 'rb'))

5.34 ms ± 462 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [137]:
%%timeit
pickle.load(open('/home/matej/sm2v3.pkl', 'rb'))

4.91 ms ± 92.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [138]:
%%timeit
pickle.load(open('/home/matej/sm2v4.pkl', 'rb'))

4.4 ms ± 113 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [132]:
pickle.load(open('/home/matej/sm2.pkl', 'rb'))

{'tsq508': 'tfc3-g349e',
 'yal001c': 'tfc3-g349e',
 'tfc3': 'tfc3-g349e',
 'tau 138': 'tfc3-g349e',
 'tsv115': 'tfc3-g349e',
 'fun24': 'tfc3-g349e',
 'sn273': 'vps8',
 'yal002w': 'vps8',
 'vpl8': 'vps8',
 'vpt8': 'vps8',
 'fun15': 'vps8',
 'sn2532': 'fun14',
 'yal008w': 'fun14',
 'mcp3': 'fun14',
 'sn1073': 'spo7',
 'yal009w': 'spo7',
 'sn2699': 'mdm10',
 'yal010c': 'mdm10',
 'fun37': 'mdm10',
 'sn1778': 'swc3',
 'yal011w': 'swc3',
 'swc1': 'swc3',
 'sn4470': 'cys3',
 'yal012w': 'cys3',
 'str1': 'cys3',
 'fun35': 'cys3',
 'cyi1': 'cys3',
 'sn2007': 'dep1',
 'yal013w': 'dep1',
 'fun54': 'dep1',
 'sn4677': 'syn8',
 'yal014c': 'syn8',
 'syntaxin': 'syn8',
 'slt2': 'syn8',
 'uip2': 'syn8',
 'sn1277': 'ntg1',
 'yal015c': 'ntg1',
 'ogg2': 'ntg1',
 'scr1': 'ntg1',
 'fun33': 'ntg1',
 'sn4628': 'yal016c-b',
 'sn2937': 'psk1',
 'yal017w': 'psk1',
 'fun31': 'psk1',
 'sn3084': 'lds1',
 'yal018c': 'lds1',
 'sn1217': 'fun30',
 'yal019w': 'fun30',
 'sn1168': 'ats1',
 'yal020c': 'ats1',
 'kti13': 'ats1',
 'fun28': 'ats1',
 'sn1991': 'ccr4',
 'yal021c': 'ccr4',
 'nut21': 'ccr4',
 'fun27': 'ccr4',
 'sn2248': 'fun26',
 'yal022c': 'fun26',
 'sn870': 'pmt2',
 'yal023c': 'pmt2',
 'fun25': 'pmt2',
 'sn1594': 'lte1',
 'yal024c': 'lte1-supp1',
 'msi2': 'lte1-supp1',
 'tsq1295': 'mak16-5001',
 'yal025c': 'mak16-5001',
 'mak16': 'mak16-5001',
 'sn3723': 'saw1',
 'yal027w': 'saw1',
 'sn178': 'snc1',
 'yal030w': 'snc1',
 'sn3064': 'fun19',
 'yal034c': 'fun19',
 'tsq1259': 'mtw1-ts',
 'yal034w-a': 'mtw1-ts',
 'mtw1': 'mtw1-ts',
 'nsl2': 'mtw1-ts',
 'dsn3': 'mtw1-ts',
 'sn3892': 'rbg1',
 'yal036c': 'rbg1',
 'fun11': 'rbg1',
 'sn4629': 'yal037c-a',
 'sn3085': 'yal037w',
 'tsq26': 'cdc19-1',
 'yal038w': 'cdc19-1',
 'cdc19': 'cdc19-1',
 'pyk1': 'cdc19-1',
 'sn2635': 'cyc3',
 'yal039c': 'cyc3',
 'cchl': 'cyc3',
 'sn1334': 'cln3',
 'yal040c': 'cln3',
 'cyclin cln3': 'cln3',
 'whi1': 'cln3',
 'fun10': 'cln3',
 'daf1': 'cln3',
 'tsq1065': 'cdc24-h',
 'yal041w': 'cdc24-h',
 'cdc24': 'cdc24-h',
 'cls4': 'cdc24-h',
 'tsq1250': 'cdc24-4',
 'tsq148': 'cdc24-11',
 'tsq408': 'cdc24-1',
 'tsq410': 'cdc24-2',
 'tsq412': 'cdc24-3',
 'sn197': 'erv46',
 'yal042w': 'erv46',
 'fun9': 'erv46',
 'tsq1367': 'pta1-5001',
 'yal043c': 'pta1-5001',
 'pta1': 'pta1-5001',
 'fun39': 'pta1-5001',
 'sn3086': 'bol1',
 'yal044w-a': 'bol1',
 'sn3087': 'bol3',
 'yal046c': 'bol3',
 'aim1': 'bol3',
 'sn533': 'gem1',
 'yal048c': 'gem1',
 'gon1': 'gem1',
 'sn3422': 'aim2',
 'yal049c': 'aim2',
 'protein aim2': 'aim2',
 'sn1911': 'oaf1',
 'yal051w': 'oaf1',
 'yaf1': 'oaf1',
 'sn640': 'flc2',
 'yal053w': 'flc2',
 'huf2': 'flc2',
 'sn2738': 'acs1',
 'yal054c': 'acs1',
 'fun44': 'acs1',
 'sn380': 'pex22',
 'yal055w': 'pex22',
 'yaf5': 'pex22',
 'sn2724': 'gpb2',
 'yal056w': 'gpb2',
 'krh1': 'gpb2',
 'sn2203': 'cne1',
 'yal058w': 'cne1',
 'calnexin': 'cne1',
 'fun48': 'cne1',
 'sn3907': 'ecm1',
 'yal059w': 'ecm1',
 'sn2617': 'bdh2',
 'yal061w': 'bdh2',
 'sn4337': 'gdh3',
 'yal062w': 'gdh3',
 'fun51': 'gdh3',
 'sn4630': 'yal063c-a',
 'sn827': 'flo9',
 'yal063c': 'flo9',
 'flocculin flo9': 'flo9',
 'sn3088': 'tda8',
 'yal064c-a': 'tda8',
 'yal065c-a': 'tda8',
 'sn2236': 'seo1',
 'yal067c': 'seo1',
 'sn4679': 'pau8',
 'yal068c': 'pau8',
 'sn1908': 'nup60',
 'yar002w': 'nup60',
 'sn1799': 'swd1',
 'yar003w': 'swd1',
 'saf49': 'swd1',
 'cps50': 'swd1',
 'fun16': 'swd1',
 'sn784': 'bud14',
 'yar014c': 'bud14',
 'sn1226': 'kin3',
 'yar018c': 'kin3',
 'npk1': 'kin3',
 'fun52': 'kin3',
 'tsq1185': 'cdc15-1',
 'yar019c': 'cdc15-2',
 'cdc15': 'cdc15-2',
 'lyt1': 'cdc15-2',
 'sn4681': 'yar023c',
 'tsq1352': 'aar2-5001',
 'ybl074c': 'aar2-5001',
 'aar2': 'aar2-5001',
 'sn3713': 'uip3',
 'yar027w': 'uip3',
 'sn3091': 'yar028w',
 'sn3423': 'yar029w',
 'sn4682': 'mst28',
 'yar033w': 'mst28',
 'sn4632': 'yar035c-a',
 'sn3004': 'swh1',
 'yar042w': 'swh1',
 'osh1': 'swh1',
 'yar044w': 'swh1',
 'sn824': 'flo1',
 'yar050w': 'flo1',
 'flocculin flo1': 'flo1',
 'flo4': 'flo1',
 'flo2': 'flo1',
 'sn3095': 'yar066w',
 'sn2924': 'pho11',
 'yar071w': 'pho11',
 'sn4296': 'yar075w',
 'sn720': 'ecm15',
 'ybl001c': 'ecm15',
 'sn1756': 'htb2',
 'ybl002w': 'htb2',
 'histone h2b': 'htb2',
 'sn1755': 'hta2',
 'ybl003c': 'hta2',
 'histone h2a': 'hta1',
 'h2a2': 'hta2',
 'sn1998': 'pdr3',
 'ybl005w': 'pdr3',
 'tpe2': 'pdr3',
 'amy2': 'pdr3',
 'sn699': 'ldb7',
 'ybl006c': 'ldb7',
 'rsc14': 'ldb7',
 'sn761': 'sla1',
 'ybl007c': 'sla1',
 'sn4633': 'ybl008w-a',
 'sn1371': 'alk2',
 'ybl009w': 'alk2',
 'sn894': 'sct1',
 'ybl011w': 'sct1',
 'gat2': 'sct1',
 'sn4215': 'fmt1',
 'ybl013w': 'fmt1',
 'sn545': 'ach1',
 'ybl015w': 'ach1',
 'sn1264': 'apn2',
 'ybl019w': 'apn2',
 'eth1': 'apn2',
 'sn2127': 'hap3',
 'ybl021c': 'hap3',
 'tsq111': 'mcm2-1',
 'ybl023c': 'mcm2-1',
 'mcm2': 'mcm2-1',
 'sn4219': 'ncl1',
 'ybl024w': 'ncl1',
 'trm4': 'ncl1',
 'tsq1294': 'lsm2-5001',
 'ybl026w': 'lsm2-5001',
 'lsm2': 'lsm2-5001',
 'snp3': 'lsm2-5001',
 'smx5': 'lsm2-5001',
 'sn662': 'ybl028c',
 'sn3097': 'ybl029c-a',
 'sn1113': 'she1',
 'ybl031w': 'she1',
 'sn1649': 'hek2',
 'ybl032w': 'hek2',
 'khd1': 'hek2',
 'tsq274': 'stu1-5',
 'ybl034c': 'stu1-7',
 'stu1': 'stu1-7',
 'tsq454': 'stu1-8',
 'tsq643': 'stu1-6',
 'tsq822': 'stu1-12',
 'tsq953': 'stu1-7',
 'tsq365': 'pol12-ts',
 'ybl035c': 'pol12-ts',
 'pol12': 'pol12-ts',
 'sn524': 'apl3',
 'ybl037w': 'apl3',
 'sn4425': 'ura7',
 'ybl039c': 'ura7',
 'sn4634': 'ybl039w-b',
 'ybl039w-a': 'ybl039w-b',
 'tsq1293': 'pre7-5001',
 'ybl041w': 'pre7-5001',
 'pre7': 'pre7-5001',
 'prs3': 'pre7-5001',
 'sn2394': 'fui1',
 'ybl042c': 'fui1',
 'sn711': 'ecm13',
 'ybl043w': 'ecm13',
 'sn3098': 'ybl044w',
 'sn3724': 'psy4',
 'ybl046w': 'psy4',
 'hsm6': 'psy4',
 'sn164': 'ede1',
 'ybl047c': 'ede1',
 'bud15': 'ede1',
 'sn3073': 'moh1',
 'ybl049w': 'moh1',
 'tsq48': 'sec17-1',
 'ybl050w': 'sec17-1',
 'sec17': 'sec17-1',
 'rns3': 'sec17-1',
 'sn1352': 'pin4',
 'ybl051c': 'pin4',
 'mdt1': 'pin4',
 'sn1794': 'sas3',
 'ybl052c': 'sas3',
 'kat6': 'sas3',
 'sn3424': 'ybl055c',
 'tat-d': 'ybl055c',
 'sn3843': 'pth2',
 'ybl057c': 'pth2',
 'sn1072': 'shp1',
 'ybl058w': 'shp1',
 'ubx1': 'shp1',
 'sn3551': 'cmc2',
 'ybl059c-a': 'cmc2',
 'sn2543': 'ybl059w',
 'sn3552': 'yel1',
 'ybl060w': 'yel1',
 'sn1237': 'skt5',
 'ybl061c': 'skt5',
 'csd4': 'skt5',
 'chs4': 'skt5',
 'cal2': 'skt5',
 'sn1436': 'kip1',
 'ybl063w': 'kip1',
 'cin9': 'kip1',
 'sn1586': 'prx1',
 'ybl064c': 'prx1',
 'sn624': 'sef1',
 'ybl066c': 'sef1',
 'sn1167': 'ubp13',
 'ybl067c': 'ubp13',
 'sn4357': 'prs4',
 'ybl068w': 'prs4',
 'sn374': 'ast1',
 'ybl069w': 'ast1',
 'sn4015': 'rps8a',
 'ybl072c': 'rps8a',
 'es8': 'rps8a',
 's8e': 'rps8a',
 'rp19': 'rps8a',
 'ys9': 'rps8a',
 's8a': 'rps8a',
 's14a': 'rps14a',
 'sn443': 'ssa3',
 'ybl075c': 'ssa3',
 'yg106': 'ssa3',
 'tsq275': 'ils1-1',
 'ybl076c': 'ils1-1',
 'ils1': 'ils1-1',
 'sn395': 'atg8',
 'ybl078c': 'atg8',
 'aut7': 'atg8',
 'cvt5': 'atg8',
 'apg8': 'atg8',
 'sn1865': 'nup170',
 'ybl079w': 'nup170-supp1',
 'nle3': 'nup170-supp1',
 'sn2688': 'pet112',
 'ybl080c': 'pet112',
 'sn3099': 'ybl081w',
 'sn914': 'alg3',
 'ybl082c': 'alg3',
 'rhk1': 'alg3',
 'tsq92': 'cdc27-1',
 'ybl084c': 'cdc27-2',
 'cdc27': 'cdc27-2',
 'snb1': 'cdc27-2',
 'apc3': 'cdc27-2',
 'tsq93': 'cdc27-2',
 'sn815': 'boi1',
 'ybl085w': 'boi1',
 'bob1': 'cdc46-1',
 'gin7': 'boi1',
 'sn2143': 'ybl086c',
 'sn3959': 'rpl23a',
 'ybl087c': 'rpl23a',
 'ul14': 'rpl23a',
 'l14': 'rpl23a',
 'yl32': 'rpl23a',
 'l23a': 'rpl23a',
 'l17aa': 'rpl23a',
 'sn1616': 'tel1',
 'ybl088c': 'tel1',
 'sn4683': 'avt5',
 'ybl089w': 'avt5',
 'sn3818': 'scs22',
 'ybl091c-a': 'scs22',
 'sn4151': 'map2',
 'ybl091c': 'map2',
 'sn2544': 'mrx3',
 'ybl095w': 'mrx3',
 'tsq510': 'brn1-9',
 'ybl097w': 'brn1-16',
 'brn1': 'brn1-16',
 'tsq511': 'brn1-16',
 'sn4394': 'bna4',
 'ybl098w': 'bna4',
 'sn4636': 'ybl100w-c',
 'ybl101w-c': 'ybl100w-c',
 'sn146': 'ecm21',
 'ybl101c': 'ecm21',
 'art2': 'ecm21',
 'sn236': 'sft2',
 'ybl102w': 'sft2',
 'sn2104': 'rtg3',
 'ybl103c': 'rtg3',
 'sn51': 'sea4',
 'ybl104c': 'sea4',
 'ybl103c-a': 'sea4',
 'tsq535': 'pkc1-ts',
 'ybl105c': 'pkc1-3',
 'pkc1': 'pkc1-3',
 'cly7': 'pkc1-3',
 'cly5': 'pkc1-3',
 'stt1': 'pkc1-3',
 'hpo2': 'pkc1-3',
 'cly15': 'pkc1-3',
 'tsq537': 'pkc1-1',
 'tsq538': 'pkc1-2',
 'tsq539': 'pkc1-4',
 'tsq541': 'pkc1-3',
 'sn4637': 'pau9',
 'ybl108c-a': 'pau9',
 'sn3100': 'ybl111c',
 'sn2972': 'nth2',
 'ybr001c': 'nth2',
 'sn2732': 'coq1',
 'ybr003w': 'coq1',
 'sn4458': 'uga2',
 'ybr006w': 'uga2',
 'uga5': 'uga2',
 'sn3063': 'dsf2',
 'ybr007c': 'dsf2',
 'sn1751': 'hhf1',
 'ybr009c': 'hhf1',
 'histone h4': 'hhf2',
 'sn1757': 'hht1',
 'ybr010w': 'hht1',
 'histone h3': 'hht2',
 'sin2': 'hht1',
 'bur5': 'hht1',
 'tsq1291': 'ipp1-5001',
 'ybr011c': 'ipp1-5001',
 'ipp1': 'ipp1-5001',
 'ppa1': 'ipp1-5001',
 'sn139': 'grx7',
 'ybr014c': 'grx7',
 'sn908': 'mnn2',
 'ybr015c': 'mnn2',
 'ldb8': 'mnn2',
 'crv4': 'mnn2',
 'ttp1': 'mnn2',
 'sn3858': 'ybr016w',
 'sn2839': 'gal7',
 'ybr018c': 'gal7',
 'sn2838': 'gal10',
 'ybr019c': 'gal10',
 'sn2836': 'gal1',
 'ybr020w': 'gal1',
 'galactokinase': 'gal1',
 'sn3044': 'poa1',
 'ybr022w': 'poa1',
 'sn1236': 'chs3',
 'ybr023c': 'chs3',
 'kti2': 'chs3',
 'dit101': 'chs3',
 'csd2': 'chs3',
 'cal1': 'cdc43-2',
 'sn2280': 'sco2',
 'ybr024w': 'sco2',
 'sn3426': 'ola1',
 'ybr025c': 'ola1',
 'obg-like atpase': 'ola1',
 'sn4684': 'etr1',
 'ybr026c': 'etr1',
 "mrf1'": 'etr1',
 'mrf1': 'mrf1-supp1',
 'sn3797': 'ypk3',
 'ybr028c': 'ypk3',
 'tsq1292': 'cds1-5001',
 'ybr029c': 'cds1-5001',
 'cds1': 'cds1-5001',
 'cdg1': 'cds1-5001',
 'sn897': 'rkm3',
 'ybr030w': 'rkm3',
 'sn3981': 'rpl4a',
 'ybr031w': 'rpl4a',
 'ul4': 'rpl4a',
 'l4': 'rpl4a',
 'rp2': 'rpl4a',
 'yl2': 'rpl4a',
 'l4a': 'rpl8a',
 'l2a': 'rpl2a',
 'sn620': 'eds1',
 'ybr033w': 'eds1',
 'sn1856': 'hmt1',
 'ybr034c': 'hmt1',
 'rmt1': 'hmt1',
 'odp1': 'hmt1',
 'hcp1': 'hmt1',
 'sn2818': 'pdx3',
 'ybr035c': 'pdx3',
 'sn2202': 'csg2',
 'ybr036c': 'csg2',
 'cls2': 'csg2',
 'sn2703': 'sco1',
 'ybr037c': 'sco1',
 'pet161': 'sco1',
 'sn782': 'fig1',
 'ybr040w': 'fig1',
 'sn2400': 'fat1',
 'ybr041w': 'fat1',
 'sn892': 'cst26',
 'ybr042c': 'cst26',
 'psi1': 'cst26',
 'sn2402': 'qdr3',
 'ybr043c': 'qdr3',
 'aqr2': 'qdr3',
 'sn2696': 'tcm62',
 'ybr044c': 'tcm62',
 'sn3663': 'zta1',
 'ybr046c': 'zta1',
 'sn2511': 'fmp23',
 'ybr047w': 'fmp23',
 'sn4112': 'rps11b',
 'ybr048w': 'rps11b',
 'us17': 'rps11b',
 's17': 'sec12-1-supp1',
 'rp41b': 'rps11b',
 'ys12': 'rps11b',
 's18b': 'rps18b',
 's11b': 'rps11b',
 'sn3103': 'ybr053c',
 'sn659': 'yro2',
 'ybr054w': 'yro2',
 'tsq1110': 'prp6-ts',
 'ybr055c': 'prp6-1',
 'prp6': 'prp6-1',
 'tsm7269': 'prp6-1',
 'rna6': 'prp6-1',
 'tsq455': 'prp6-1',
 'sn4638': 'ybr056w-a',
 'sn2769': 'ybr056w',
 'sn1519': 'mum2',
 'ybr057c': 'mum2',
 'spot8': 'mum2',
 'sn2944': 'ubp14',
 'ybr058c': 'ubp14',
 'gid6': 'ubp14',
 'sn558': 'akl1',
 'ybr059c': 'akl1',
 'tsq295': 'orc2-1',
 'ybr060c': 'orc2-3',
 'orc2': 'orc2-3',
 'sir5': 'orc2-3',
 'rrr1': 'orc2-3',
 'tsq309': 'orc2-4',
 'tsq311': 'orc2-2',
 'tsq331': 'orc2-3',
 'sn3104': 'ybr062c',
 'sn3105': 'ybr063c',
 'sn1749': 'ecm2',
 'ybr065c': 'ecm2',
 'slt11': 'ecm2',
 'sn1824': 'nrg2',
 'ybr066c': 'nrg2',
 'sn2335': 'bap2',
 'ybr068c': 'bap2',
 'sn2336': 'tat1',
 'ybr069c': 'tat1',
 'vap1': 'tat1',
 'tap1': 'rat1-1-supp1',
 'tsq1290': 'alg14-5001',
 'ybr070c': 'alg14-5001',
 'alg14': 'alg14-5001',
 'sn3428': 'ybr071w',
 'sn4639': 'ybr072c-a',
 'sn1420': 'rdh54',
 'ybr073w': 'rdh54',
 'tid1': 'rdh54',
 'sn145': 'ecm8',
 'ybr076w': 'ecm8',
 'sn1027': 'slm4',
 'ybr077c': 'slm4',
 'gse1': 'slm4',
 'nir1': 'slm4',
 'ego3': 'slm4',
 'tsq1289': 'rpg1-5001',
 'ybr079c': 'rpg1-1',
 'rpg1': 'rpg1-1',
 'tif32': 'rpg1-1',
 'tsq992': 'rpg1-1',
 'tsq57': 'sec18-1',
 'ybr080c': 'sec18-1',
 'sec18': 'sec18-1',
 'anu4': 'sec18-1',
 'sn1021': 'ubc4',
 'ybr082c': 'ubc4',
 'sn3949': 'rpl19a',
 'ybr084c-a': 'rpl19a',
 'el19': 'rpl19b',
 'l19e': 'rpl19b',
 'rpl5l': 'rpl19b',
 'yl14': 'rpl19b',
 'l19a': 'rpl19a',
 'sn2684': 'mis1',
 'ybr084w': 'mis1',
 'sn4640': 'ybr085c-a',
 'sn2491': 'aac3',
 'ybr085w': 'aac3',
 'anc3': 'aac3',
 'sn991': 'ist2',
 'ybr086c': 'ist2',
 'tsq887': 'rfc5-1',
 'ybr087w': 'rfc5-1',
 'rfc5': 'rfc5-1',
 'sn1997': 'nhp6b',
 'ybr089c-a': 'nhp6b',
 'ybr090c-a': 'nhp6b',
 'sn3553': 'ybr090c',
 'sn2925': 'pho5',
 'ybr093c': 'pho5',
 'phoe': 'pho5',
 'sn1121': 'pby1',
 'ybr094w': 'pby1',
 'sn841': 'rxt2',
 'ybr095c': 'rxt2',
 'raf60': 'rxt2',
 'sn72': 'ybr096w',
 'sn1294': 'mms4',
 'ybr098w': 'mms4',
 'ybr100w': 'mms4',
 'slx2': 'mms4',
 'sn3842': 'fes1',
 'ybr101c': 'fes1',
 'tsq24': 'exo84-102',
 'ybr102c': 'exo84-102',
 'exo84': 'exo84-102',
 'usa3': 'exo84-102',
 'sn1797': 'sif2',
 'ybr103w': 'sif2',
 'emb1': 'sif2',
 'sn2265': 'ymc2',
 'ybr104w': 'ymc2',
 'sn539': 'vid24',
 'ybr105c': 'vid24',
 'gid4': 'vid24',
 'sn1220': 'iml3',
 'ybr107c': 'iml3',
 'mcm19': 'iml3',
 'sn1122': 'aim3',
 'ybr108w': 'aim3',
 'tsq1085': 'cmd1-3',
 'ybr109c': 'cmd1-8',
 'cmd1': 'cmd1-8',
 'calmodulin': 'cmd1-3',
 'cam': 'cmd1-8',
 'tsq154': 'cmd1-1',
 'tsq157': 'cmd1-8',
 'tsq1087': 'alg1-1',
 'ybr110w': 'alg1-1',
 'alg1': 'alg1-1',
 'sn4312': 'ysa1',
 'ybr111c': 'ysa1',
 'rma2': 'ysa1',
 'sn4641': 'sus1',
 'ybr111w-a': 'sus1',
 'sn1779': 'cyc8',
 'ybr112c': 'cyc8',
 '[oct]': 'cyc8',
 '[oct1+]': 'cyc8',
 'ssn6': 'cyc8',
 'crt8': 'cyc8',
 'sn1510': 'rad16',
 'ybr114w': 'rad16',
 'pso5': 'rad16',
 'sn2920': 'tkl2',
 'ybr117c': 'tkl2',
 'sn4201': 'tef2',
 'ybr118w': 'tef2',
 'eef1a': 'tef2',
 'ef-1 alpha': 'tef2',
 'sn1892': 'mud1',
 'ybr119w': 'mud1',
 'u1a': 'mud1',
 'u1-a': 'mud1',
 'sn3936': 'cbp6-supp1',
 'ybr120c': 'cbp6-supp1',
 'cbp6': 'cbp6-supp1',
 'tsq568': 'tfc1-e447k',
 'ybr123c': 'tfc1-e447k',
 'tfc1': 'tfc1-e447k',
 'tau 95': 'tfc1-e447k',
 'sn1157': 'ptc4',
 'ybr125c': 'ptc4',
 'gct1': 'ptc4',
 'sn2975': 'tps1',
 'ybr126c': 'tps1-supp1',
 'tss1': 'tps1-supp1',
 'glc6': 'tps1-supp1',
 'ggs1': 'tps1-supp1',
 'fdp1': 'tps1-supp1',
 'cif1': 'tps1-supp1',
 'byp1': 'tps1-supp1',
 'sn10': 'atg14',
 'ybr128c': 'atg14',
 'apg14': 'atg14',
 'cvt12': 'atg14',
 'sn791': 'opy1',
 'ybr129c': 'opy1',
 'sn834': 'she3',
 'ybr130c': 'she3',
 'sn428': 'ccz1',
 'ybr131w': 'ccz1',
 'cvt16': 'ccz1',
 'sn2191': 'agp2',
 'ybr132c': 'agp2',
 'tsq1105': 'cks1-38',
 'ybr135w': 'cks1-35',
 'cks1': 'cks1-35',
 'tsq1490': 'mec1-4ts',
 'ybr136w': 'mec1-4ts',
 'mec1': 'mec1-4ts',
 'rad31': 'mec1-4ts',
 'sad3': 'mec1-4ts',
 'esr1': 'mec1-4ts',
 'sn3429': 'ybr137w',
 'sn1123': 'ybr138c',
 'hdr1': 'ybr138c',
 'sn2443': 'ybr139w',
 'sn3717': 'bmt2',
 'ybr141c': 'bmt2',
 'tsq1361': 'mak5-5001',
 'ybr142w': 'mak5-5001',
 'mak5': 'mak5-5001',
 'tsq1215': 'sup45-ts',
 'ybr143c': 'sup45-ts',
 'sup45': 'sup45-ts',
 'erf1': 'sup45-ts',
 'sup47': 'sup45-ts',
 'sup1': 'sup45-ts',
 'sal4': 'sup45-ts',
 'sn2740': 'adh5',
 'ybr145w': 'adh5',
 'sn4060': 'mrps9',
 'ybr146w': 'mrps9',
 'sn3107': 'rtc2',
 'ybr147w': 'rtc2',
 'ypq3': 'rtc2',
 'rrt11': 'rtc2',
 'sn637': 'ysw1',
 'ybr148w': 'ysw1',
 'sn2794': 'ara1',
 'ybr149w': 'ara1',
 'sn1713': 'tbs1',
 'ybr150c': 'tbs1',
 'tsq1304': 'spp381-5001',
 'ybr152w': 'spp381-5001',
 'spp381': 'spp381-5001',
 'tsq1302': 'rib7-5001',
 'ybr153w': 'rib7-5001',
 'rib7': 'rib7-5001',
 'tsq1373': 'rpb5-5001',
 'ybr154c': 'rpb5-5001',
 'rpb5': 'rpb5-5001',
 'abc27': 'rpb5-5001',
 'tsq236': 'sli15-3',
 'ybr156c': 'sli15',
 'sli15': 'sli15-3',
 'sn3069': 'ics2',
 'ybr157c': 'ics2',
 'tsq150': 'cdc28-4',
 'ybr160w': 'cdc28-td',
 'cdc28': 'cdc28-td',
 'srm5': 'cdc28-td',
 'hsl5': 'cdc28-td',
 'cdk1': 'cdc28-td',
 'tsq175': 'cdc28-13',
 'tsq65': 'cdc28-td',
 'sn2990': 'csh1',
 'ybr161w': 'csh1',
 'sn3055': 'tos1',
 'ybr162c': 'tos1',
 'sn360': 'ysy6',
 'ybr162w-a': 'ysy6',
 'sn2502': 'exo5',
 'ybr163w': 'exo5',
 'dem1': 'exo5',
 'sn432': 'arl1',
 'ybr164c': 'arl1',
 'dlp2': 'arl1',
 'sn1964': 'ubs1',
 'ybr165w': 'ubs1',
 'sn4488': 'tyr1',
 'ybr166c': 'tyr1',
 'tsq1303': 'pop7-5001',
 'ybr167c': 'pop7-5001',
 'pop7': 'pop7-5001',
 'rpp2': 'pop7-5001',
 'sn4685': 'pex32',
 'ybr168w': 'pex32-supp1',
 'sn342': 'sse2',
 'ybr169c': 'sse2',
 'sn320': 'sec66',
 'ybr171w': 'sec66',
 'kar7': 'sec66',
 'sec71': 'sec66',
 'hss1': 'sec66',
 'sn159': 'smy2',
 'ybr172c': 'smy2',
 'sn2177': 'ump1',
 'ybr173c': 'ump1',
 'rns2': 'ump1',
 'sn1205': 'swd3',
 'ybr175w': 'swd3',
 'saf35': 'swd3',
 'cps30': 'swd3',
 'sn2649': 'eht1',
 'ybr177c': 'eht1',
 'sn2673': 'fzo1',
 'ybr179c': 'fzo1',
 'mitofusin': 'fzo1',
 'sn2411': 'dtr1',
 'ybr180w': 'dtr1',
 'sn3943': 'rps6b',
 'ybr181c': 'rps6b',
 'es6': 'rps6a',
 's6e': 'rps6a',
 'rps102': 'rps6b',
 'rps101': 'rps6b',
 'lpg18': 'rps6b',
 'sn4642': 'ybr182c-a',
 'sn1924': 'smp1',
 'ybr182c': 'smp1',
 'sn2800': 'ypc1',
 'ybr183w': 'ypc1',
 'phytoceramidase': 'ypc1',
 'sn3108': 'ybr184w',
 'sn4686': 'mba1',
 'ybr185c': 'mba1',
 'sn1596': 'pch2',
 'ybr186w': 'pch2',
 'sn3767': 'gdt1',
 'ybr187w': 'gdt1',
 'sn1898': 'ntc20',
 'ybr188c': 'ntc20',
 'sn3955': 'rpl21a',
 'ybr191w': 'rpl21a',
 'el21': 'rpl21b',
 'l21e': 'rpl21b',
 'l21a': 'rpl16a',
 'urp1': 'rpl21a',
 'tsq741': 'med8-51',
 'ybr193c': 'med8-39',
 'med8': 'med8-39',
 'sn1704': 'aim4',
 'ybr194w': 'aim4',
 'soy1': 'aim4',
 'sn1296': 'msi1',
 'ybr195c': 'msi1',
 'cac3': 'msi1',
 'sn4643': 'ybr196c-a',
 'sn4644': 'ybr196c-b',
 'tsq94': 'pgi1-2',
 'ybr196c': 'pgi1-2',
 'pgi1': 'pgi1-2',
 'cdc30': 'pgi1-2',
 'sn3554': 'ybr197c',
 'tsq512': 'taf5-15',
 'ybr198c': 'taf5-3',
 'taf5': 'taf5-3',
 'tafii90': 'taf5-3',
 'taf90': 'taf5-3',
 'tsq513': 'taf5-20',
 'sn4645': 'ybr200w-a',
 'sn817': 'bem1',
 'ybr200w': 'bem1',
 'sro1': 'bem1',
 'sn219': 'der1',
 'ybr201w': 'der1',
 'derlin': 'der1',
 'tsq1080': 'cdc47-ts',
 'ybr202w': 'cdc47-ts',
 'mcm7': 'cdc47-ts',
 'cdc47': 'cdc47-ts',
 'sn3868': 'cos111',
 'ybr203w': 'cos111',
 'sn751': 'ktr3',
 'ybr205w': 'ktr3',
 'sn180': 'fth1',
 'ybr207w': 'fth1',
 'sn4253': 'dur1,2',
 'ybr208c': 'dur1,2',
 'dur80': 'dur1,2',
 'sn594': 'erv15',
 'ybr210w': 'erv15',
 'tsq716': 'ame1-4',
 'ybr211c': 'ame1-4',
 'ame1': 'ame1-4',
 'arp100': 'ame1-4',
 'sn1826': 'ngr1',
 'ybr212w': 'ngr1',
 'rbp1': 'fpr1',
 'sn4466': 'met8',
 'ybr213w': 'met8',
 'sn1325': 'sds24',
 'ybr214w': 'sds24',
 'sn1345': 'hpc2',
 'ybr215w': 'hpc2',
 'sn3860': 'ybp1',
 'ybr216c': 'ybp1',
 'sn426': 'atg12',
 'ybr217w': 'atg12',
 'apg12': 'atg12',
 'sn2853': 'pyc2',
 'ybr218c': 'pyc2',
 'sn3110': 'ybr220c',
 'sn4687': 'pdb1',
 'ybr221c': 'pdb1',
 'sn4492': 'ybr221w-a',
 'sn1267': 'tdp1',
 'ybr223c': 'tdp1',
 'sn3111': 'ybr225w',
 'sn2622': 'mcx1',
 'ybr227c': 'mcx1',
 'sn1271': 'slx1',
 'ybr228w': 'slx1',
 'endonuclease': 'slx1',
 'sn696': 'rot2',
 'ybr229c': 'rot2',
 'gls2': 'rot2',
 'sn2545': 'om14',
 'ybr230c': 'om14',
 'sn4646': 'ybr230w-a',
 'sn1102': 'pbp2',
 'ybr233w': 'pbp2',
 'hek1': 'pbp2',
 'tsq1299': 'arc40-5001',
 'ybr234c': 'arc40-5001',
 'arc40': 'arc40-5001',
 'sn2142': 'vhc1',
 'ybr235w': 'vhc1',
 'tsq357': 'abd1-8',
 'ybr236c': 'abd1-8',
 'abd1': 'abd1-8',
 'tsq78': 'abd1-5',
 'tsq117': 'prp5-1',
 'ybr237w': 'prp5-1',
 'prp5': 'prp5-1',
 'rna5': 'prp5-1',
 'sn651': 'ybr238c',
 'sn1715': 'ert1',
 'ybr239c': 'ert1',
 'sn1946': 'thi2',
 'ybr240c': 'thi2',
 'phof': 'thi2',
 'pho6': 'thi2',
 'sn3555': 'ybr242w',
 'sn997': 'gpx2',
 'ybr244w': 'gpx2',
 'ami1': 'gpx2',
 'sn1192': 'isw1',
 'ybr245c': 'isw1',
 'sgn2': 'isw1',
 'sn3112': 'rrt2',
 'ybr246w': 'rrt2',
 'dph7': 'rrt2',
 'ere1': 'rrt2',
 'sn4273': 'aro4',
 'ybr249c': 'aro4',
 'sn3113': 'spo23',
 'ybr250w': 'spo23',
 'tsq1398': 'trs20-5001',
 'ybr254c': 'trs20-5001',
 'trs20': 'trs20-5001',
 'sn4647': 'rcf3',
 'ybr255c-a': 'rcf3',
 'sn1124': 'mtc4',
 'ybr255w': 'mtc4',
 'sn1363': 'shg1',
 'ybr258c': 'shg1',
 'cps15': 'shg1',
 'sn879': 'rgd1',
 'ybr260c': 'rgd1',
 'sn4406': 'shm1',
 'ybr263w': 'shm1',
 'tmp3': 'shm1',
 'shmt1': 'shm1',
 'sn234': 'ypt10',
 'ybr264c': 'ypt10',
 'tsq543': 'tsc10-1',
 'ybr265w': 'tsc10-1',
 'tsc10': 'tsc10-1',
 'sn687': 'rei1',
 'ybr267w': 'rei1-supp1',
 'sn4040': 'mrpl37',
 'ybr268w': 'mrpl37',
 'yml37': 'mrpl37',
 'sn2509': 'sdh8',
 'ybr269c': 'sdh8',

In [142]:
optp = pickletools.optimize(pickle.dumps(sm2, protocol=4))

In [144]:
with open('/home/matej/sm2opt.pkl', 'wb') as fout:
    fout.write(optp)

In [146]:
%%timeit
pickle.load(open('/home/matej/sm2opt.pkl', 'rb'))

4.01 ms ± 63.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [148]:
x = p.DataFrame(corrs)

In [155]:
x

        PI_Min
6231  0.031620
6232  0.041250
2679  0.009177
4166  0.020359
4217  0.012814
4380  0.035593
2663  0.033185
92    0.008592
1503  0.003676
3741 -0.011269
2325  0.046005
4375 -0.057955
1485  0.005335
1247 -0.024453
645   0.008613
1793 -0.008812
4605  0.018131
2654 -0.026989
877   0.010540
3338 -0.007650
1097  0.026638
4996  0.012208
4789  0.033184
5265  0.003109
3750 -0.005375
2216 -0.001567
2061 -0.011406
1336 -0.025602
4133 -0.046654
5743 -0.002083
...        ...
3402 -0.005071
5700  0.010611
3889  0.059701
4733  0.061763
3905 -0.017552
4201 -0.017169
2711 -0.006594
861  -0.020094
2864 -0.011709
1761  0.016078
4067 -0.018710
4671 -0.063344
4659  0.005329
4791  0.014142
1724 -0.012329
4814 -0.038984
1497 -0.009222
4078  0.012072
6138 -0.007656
3543 -0.015974
1051  0.020411
3516  0.026254
226   0.003379
5171  0.038007
4620 -0.002772
4433  0.014373
6030  0.001619
5306  0.025537
1755  0.021114
1391  0.010012

[5357 rows x 1 columns]

In [156]:
sheets.PI_Min.corr(sheets.PI_Log, )

0.92191037370945295